name: Build and Push Admin admin Docker Image to GHCR and deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image and push to GHCR
        run: |
          echo "${{ secrets.DOCKER_GHCR_TOKEN }}" | docker login ghcr.io -u tapasrwth --password-stdin
          docker build -t ghcr.io/rppmain/admin:dev-${{ github.run_number }} .
          docker push ghcr.io/rppmain/admin:dev-${{ github.run_number }}
      - name: Deploy to dev environment
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
          EC2_HOST: ${{ vars.EC2_HOST }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ec2-user@${EC2_HOST} << 'EOF'
            docker rmi -f $(docker images -aq)
            echo "${{ secrets.DOCKER_GHCR_TOKEN }}" | docker login ghcr.io -u tapasrwth --password-stdin
            docker pull ghcr.io/rppmain/admin:dev-${{ github.run_number }}
            docker stop admin || true
            docker rm admin || true
            docker run -d --name admin -p 4000:3000 ghcr.io/rppmain/admin:dev-${{ github.run_number }}
          EOF
      - name: Clean up
        run: |
          docker logout ghcr.io
          docker rmi ghcr.io/rppmain/admin:dev-${{ github.run_number }} || true